server:
  port: ${PORT:8080}

spring:
  application:
    name: extblock-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/extblock}
    username: ${SPRING_DATASOURCE_USERNAME:extblock}
    password: ${SPRING_DATASOURCE_PASSWORD:extblock}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
